name: Package Testing

on:
  pull_request:
    branches:
      - dev
      - master
      - update-test

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.9]

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install pytest-cov
          pip install -e .
          pip install -r test_requirements.txt
          pip install globus-sdk==1.11.0
          pip install globus-nexus-client==0.3.0

      - name: Test with pytest
        run: |
          pytest -s tests/test_connect_client.py
